version: 0.2
phases:
  install:
    commands:
      - curl -O https://download.visualstudio.microsoft.com/download/pr/f5c74056-330b-452b-915e-d98fda75024e/18076ca3b89cd362162bbd0cbf9b2ca5/dotnet-sdk-7.0.100-rc.2.22477.23-linux-x64.tar.gz
      - sudo tar -zxvf dotnet-sdk-7.0.100-rc.2.22477.23-linux-x64.tar.gz -C /root/.dotnet
  pre_build:
    commands: 
      - dotnet restore
      
  build:
    commands:      
      - dotnet build -c Release
      
  post_build:
    commands:
      - dotnet publish -c Release -r linux-x64 -o ./build_output ./src/Hyme.API/Hyme.API.csproj --self-contained false
      - cp Procfile ./build_output
artifacts:
  files:
    - '**/*'
  base-directory: ./build_output
  discard-paths: no
