version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 7.0
  pre_build:
    commands:
      - dotnet restore ./src/Hyme.API/Hyme.API.csproj
  build:
    commands:
      - dotnet build ./src/Hyme.API/Hyme.API.csproj --configuration Release --no-restore
  post_build:
    commands:
      - dotnet publish -c Release -o ./src/Hyme.API/Hyme.API.csproj --no-build --output ./publish
artifacts:
  files:
    - '**/*'
