version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore src/Hyme.API/Program.cs
  build:
    commands:
      - dotnet build src/Hyme.API/Program.cs
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ src/Hyme.API/Program.cs
artifacts:
  files:
    - '**/*'
